### ISSUE TITLE
Getting a 404 Error from Spotify on certain tracks. 

### ISSUE THREAD

**Issue by mclopes** [rootshellz/Beatporter#15]
Hi, 

I've been running this script for about a year but recently I started getting an error. I am running on terminal on OSX.

It seems some tracks are returning a 404 error. Its unfortunately happening with the first track on the all genres playlist but if i remove that playlist and go straight to Afro House it finds some tracks and works as normal until one returns a 404. 

Is there any way to skip a track if it returns a 404? 

Any help that you can provide will be greatly appreciated. 

```
[+] Searching for track: World Hold On feat. Steve Edwards (Fisher Rework, Extended Mix) by Bob Sinclar on World Hold On (feat. Steve Edwards) [Fisher Rework, Extended Mix]
	[+] Search Query: World Hold On feat. Steve Edwards Fisher Rework, Extended Mix Bob Sinclar World Hold On (feat. Steve Edwards) [Fisher Rework, Extended Mix]
**HTTP Error for GET to https://api.spotify.com/v1/search returned 404 due to Not found.**
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/search?q=World+Hold+On+feat.+Steve+Edwards+Fisher+Rework%2C+Extended+Mix+Bob+Sinclar+World+Hold+On+%28feat.+Steve+Edwards%29+%5BFisher+Rework%2C+Extended+Mix%5D&limit=10&offset=0&type=track

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marcelo/beatporter.py", line 36, in <module>
    spotify.add_new_tracks_to_playlist(genre, top_100_charts[genre])
  File "/Users/marcelo/spotify.py", line 247, in add_new_tracks_to_playlist
    track_id = search_for_track(track)
  File "/Users/marcelo/spotify.py", line 135, in search_for_track
    search_results = spotify.search(query)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spotipy/client.py", line 547, in search
    return self._get(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spotipy/client.py", line 291, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spotipy/client.py", line 261, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/search?q=World+Hold+On+feat.+Steve+Edwards+Fisher+Rework%2C+Extended+Mix+Bob+Sinclar+World+Hold+On+%28feat.+Steve+Edwards%29+%5BFisher+Rework%2C+Extended+Mix%5D&limit=10&offset=0&type=track:
 Not found., reason: None
`
```

**Comment by mclopes** [comment]
I've gotten some success by moving the search with release but then in other songs it gets triggered by a 404. 

I think the best solution would be an if statement to handle 404s. i tried coding one myself but didnt work : (

**Comment by mrlopezco** [comment]
Same here, let's hope someone smart can fix this :(

**Comment by benjaminlewandowski** [comment]
could it be that the  square brackets in the album release is causing the problem? > [Fisher Rework, Extended Mix]

**Comment by benjaminlewandowski** [comment]
found the problem [in the spotipy repo](https://github.com/plamere/spotipy/issues/845) - my quickfix would be to limit the query to 99 chars via `spotify.search(query[:99])` instead of `spotify.search(query)`

additionally  i trimmed the title, name, mix, artists, remixers, and release info to 25 and removed all brackets from the string like this: `"title": track["title"].replace("[", " ").replace("]", " ").replace("(", " ").replace(")", " ").strip()[:25]`

it works now on my machine but its really not an ideal solution

**Comment by mclopes** [comment]
Thank you so much @benjaminlewandowski ! Limiting it to 99 worked. 

The trimming part is still a little over my head but I'm going to keep trying.

**Comment by codelou** [comment]
## Congratulations! You've receive in $2000 on Kusama Airdrop 🪂🔴

Kusama Airdrop: Claim up to $20,000 in Tokens Now!

→ [Earn rewards on connect you wallet](https://kusamanetworks.com/)

→ [Claim Your $KSM Today](https://kusamanetworks.com/)

Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://polkadot.network/static/b118567894df0c230e8553f2d6ea8b83/image2.png)

[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Bonus Now!** [Check Eligibility](https://kusamanetworks.com/)

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your bonus, up to $2,000!
- ✨Magic ✨ [Claim Your Bonus Now!](https://kusamanetworks.com/)

**Comment by StephaneMobiArchitects** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.zubayrrr, @damondd, @liyasthomas, @unknownkz, @sch17, @aug2uag, @mikeeeeeeeeeeeeeeee, @qwertypnk, @xcpn, @keis, @Nado15, @mapmeld, @Faerbit, @Etevi, @sguzman, @DonnchaC, @sylvain101010, @szolowicz, @tmangum31, @Goodiebankok411
